### ISSUE TITLE
Multiple SNI Crashes after updating to 0.99

### ISSUE THREAD

**Issue by Zehir** [alttpo/sni#46]
Hello,

I have some issues with latest SNI version 0.99. I just update from 0.85 on windows 386.

Not sure what is wrong but, I did a clean install, use the new lua connector using [snes9x-rr](https://github.com/gocha/snes9x-rr) 1.60.

I got some crash (just SNI closing) multiple times during multi world + emotracker or just only emotracker.
I notice that crases happend mostly when I got triforce pieces.

I check the logs in app data but found no error messages.

I suppose this won't help you to find the issue but ask me what you need

**Comment by JamesDunne** [comment]
Try running the x64 version instead of 386 version.

**Comment by Zehir** [comment]
> Try running the x64 version instead of 386 version.

Sure I could try in my next race but last time I had issue with a x64 sni with a x32 snes9x

**Comment by JamesDunne** [comment]
The snes9x build has no relevance to the sni build. They communicate over local TCP and x86 vs x64 is not a factor there.

**Comment by Zehir** [comment]
Worked with no issues for 2 seeds thanks
